### ISSUE TITLE
Nav-bar scroll bug on MS Edge

### ISSUE THREAD

**Issue by Rudxain** [gleam-lang/language-tour#46]
MSE has this "feature" that emulates Android's "elastic scrolling". It doesn't work with arrow-keys, only touch-screens and touch-pads (maybe even scroll-wheels?). This allows users to do silly stuff, like this:
<img width=363 alt="Navigation bar is slightly offset downwards, causing it to be rendered behind/under all other elements" src=https://github.com/gleam-lang/language-tour/assets/76864299/0bbef96a-2797-4a38-9dce-7a9379a83435>

This could (untested) be resolved by
```css
/*
`class` doesn't matter,
all `<nav>`s should have this rule.
*/
nav {
  position: fixed;
  z-index: 8; /* is this high enough? */
}
```

Versions tested:
- Microsoft Edge 122
- Windows 11
